preset = "C:/Users/yukimemi/src/github.com/yukimemi/pj-presets/web-react-firebase.toml"
applied_at = "2026-05-10T04:22:36.6807866Z"

[[templates]]
source = "github.com/yukimemi/pj-base"
rev = "e2e30a27880b9f7fcc7e91ed71ed6e553ba1bd4b"
version = "0.4.0"

[[templates]]
source = "github.com/yukimemi/pj-pnpm"
rev = "d0fd5aaa5d945a259798f1a8e336761aed4f2574"
version = "0.1.0"

[[templates]]
source = "github.com/yukimemi/pj-react-web"
rev = "675d6c53b69029cf8ff616ecf490e91d8aca3b6a"
version = "0.1.0"

[[templates]]
source = "github.com/yukimemi/pj-firebase"
rev = "ecd5e4f0e238175bc6010fe597dd8d1a9d5a4083"
version = "0.1.0"

[files.".agents/skills/renri/SKILL.md"]
once_applied = true

[files.".claude/skills/renri/SKILL.md"]
once_applied = true

[files.".env.example"]
once_applied = true

[files.".gemini/settings.json"]
content_hash = "486c974de88903113ed99b4e643432b7050e88f1031276f5263e8da7b43fe11e"

[files.".github/workflows/deploy.yml"]
once_applied = true

[files.".gitignore"]
content_hash = "99ce77ba843c5bee84182b768f18a501f6e76eef3731eb0e899997b33b7c8468"

[files."AGENTS.md"]
content_hash = "b45a0f630ae34ea195313d9b060eb99b0325a541f16c5dac36b536cb2f57b9cd"

[files."CLAUDE.md"]
content_hash = "a76b3af252969b8120128d7ce44f2b6cfdcf88c7420ee00675732f542d047529"

[files."GEMINI.md"]
content_hash = "3670f70a2f0be4013926bab6e878b90a42ad64c17899080aef4d193b246fa390"

[files.LICENSE]
once_applied = true

[files."OPENCODE.md"]
content_hash = "11993dc7feec5fca8e83934f135de33879b88f100c48aeba0729de2f57a11a48"

[files."apm.lock.yaml"]
once_applied = true

[files."apm.yml"]
once_applied = true

[files."eslint.config.js"]
once_applied = true

[files."firebase.json"]
once_applied = true

[files."firestore.rules"]
once_applied = true

[files."index.html"]
once_applied = true

[files."opencode.json"]
content_hash = "2ada1cf4347db9e98fadd67ca72cd9e29042c5bf6ab719d666b5d71f97663e81"

[files."package.json"]
once_applied = true

[files."postcss.config.js"]
content_hash = "e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc"

[files."public/favicon.svg"]
once_applied = true

[files."renri.toml"]
content_hash = "e24eaf714b320525e82754e8e72dbdc34a21435987d3728a51c840fdd0759e85"

[files."src/App.tsx"]
once_applied = true

[files."src/index.css"]
once_applied = true

[files."src/main.tsx"]
once_applied = true

[files."src/vite-env.d.ts"]
once_applied = true

[files."storage.rules"]
once_applied = true

[files."tailwind.config.js"]
once_applied = true

[files."tsconfig.app.json"]
content_hash = "b1eac9ba6cd1c01d59ebca159805e052c798d9d4ab904680b79ce3e306ea0bbd"

[files."tsconfig.json"]
content_hash = "770b4140bbb581e2dfd9ea9946ffc9c75a1d86ba7d2db5f77c83e37cbdf9d808"

[files."tsconfig.node.json"]
content_hash = "90a22c920cbc14624fb4658b58f15c875abf3234224f3933f211849c3ada3242"

[files."vercel.json"]
content_hash = "fa66adb9de8a1cb4401b55577ad9fcbb50871cf13fdf692fea217a49d1a76a13"

[files."vite.config.ts"]
once_applied = true
